---
- hosts: localhost
  validate_certs: false
  tasks:
    - name: download the script
      get_url:
        url: https://github.com/ganeshnv/firstrepo/raw/master/python.py
        url_username: ganeshnv
        url_password: jus04now
        dest: /tmp/python.py
        mode: 0755

    - name: execute python script
      command: /usr/bin/python python.py
      args:
        chdir: /tmp
