---
- hosts: localhost
  tasks:
    - name: download the script
      get_url:
        url: https://github.com/ganeshnv/firstrepo/raw/master/python.py
        dest: /tmp/python.py
        mode: 0775
        
    - name: execute python script
      command: ./python.py
      args:
        chdir: /tmp
