---
- hosts: localhost
  tasks:
    - name: download the script
      get_url:
        url: https://github.com/ganeshnv/firstrepo/raw/master/python.py
        validate_certs: false
        dest: /tmp/python.py
        mode: 0755

    - name: execute python script
      command: /usr/bin/python python.py {{ var1 }} {{ var2 }} {{ var3 }} {{ var4 }}
      args:
        chdir: /tmp



import os

URL= os.environ[1] 
PLATFORM= os.environ[2] 
SRVTYPE= os.environ[3]
ENV= os.environ[4]
